# Generated by Django 5.1.2 on 2024-10-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="description",
        ),
        migrations.AlterField(
            model_name="feature",
            name="hotel",
            field=models.CharField(max_length=100),
        ),
    ]
