# Generated by Django 5.1.2 on 2024-10-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_remove_feature_description_alter_feature_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
